### ISSUE TITLE
Low prio: Write empty includes

### ISSUE THREAD

**Issue by marcelveldt** [BigNoid/script.skinshortcuts#142]
http://forum.kodi.tv/showthread.php?tid=259210&pid=2239242#pid2239242

When using templates, the XML code is built when needed (the shortcut has condition X or Y).
This works fantastically well for writing widgets to the homemenu and even multiple widgets.

However if the condition is not true for a shortcut, the include is not written at all in the skin, causing some missing include errors in the logs.

For example, in Titan each shortcut can have up to 4 widgets and an include is set for each templated include. Well, when the user only assigned one widget a warning is written to the log.

This error could be prevented ny writing an empty xml element to skin for the include.

Definitely low prio as it's only a warning in the log and does no harm.
I'll look into it myself on a rainy day so this is just a reminder.

**Comment by ghost** [comment]
I had the same thought myself whilst adding [empty templates to MadNox](https://github.com/Ignoble61/skin.aeon.madnox/blob/skinshortcuts-dev/shortcuts/template.xml#L3476-L3481)'s template.xml file to avoid the same warnings. One thing to think about whilst doing it:-

It can't be a completely empty template - due to the way the templates are written that will just change the warning to a different include (skinshortcuts-template-[templatename]-[profilename] - and one warning for each profile, too). A simple `<description>This is an empty template</description>` is enough.

**Comment by marcelveldt** [comment]
yeah, good idea about that description element

**Comment by marcelveldt** [comment]
OK, I discussed this with ronie at the mailing list. The missing includes confuse him while checking skins for errors and off course the warning in the log is not that great. I will take a look at this later today so it can be included in the quick follow up update to the repo.

**Comment by ghost** [comment]
Any progress on this? Any assistance needed?

**Comment by marcelveldt** [comment]
Not yet had the time to look at this. Will do so later this week.
Has the final decision been made for the breaking include change or not yet ?

**Comment by ghost** [comment]
I haven't heard anything regarding the include changes. My suspicion is that Phil will get his way, though ;)
