### ISSUE TITLE
new stable version 1.0.6

### ISSUE THREAD

**Issue by marcelveldt** [BigNoid/script.skinshortcuts#144]
@Ignoble61 now that version 1.0.6 is tested for a couple of days on the beta repo it's pretty safe to say that it's stable. I requested the pull to the Kodi repo a few minutes ago.

Once it's published it's safe to start adding features/move code around again ;-)

BTW: What to do with the optional contextmenu addon ?
Do you want to submit it yourself or do you want me to do that ?

**Comment by ghost** [comment]
This might be the first time in a while I'm not away when it gets updated on the repo - hopefully that means it's guaranteed to be working perfectly so that there's no actual _need_ for me to be around ;)

If the release tagged can I not start to move code around now? (The fact that the build progress indicator pauses whilst building templates has been really bugging me this past week whilst I've been doing some actual skinning and am seeing it many times a day!) Though once that's done I shall be enjoying a break from doing anything major to the script for a while :)

As regards the context menu addon, I think it needs testing more before it goes onto the repo, particularly as the bugs will actually have to be fixed in script.skinshortcuts. Once thats on the repo I shall encourage a bit more testing of the context menu addon to ensure the feature actually works as expected before thinking about a repo push.

**Comment by marcelveldt** [comment]
the update is live now.

**Comment by ghost** [comment]
:+1:
