### ISSUE TITLE
change shortcut deletes all properties

### ISSUE THREAD

**Issue by marcelveldt** [BigNoid/script.skinshortcuts#17]
If a user wants to change the action for an existing shortcut all of the existing shortcut's properties like submenu, label, icon and stuff are lost.

I have received several complaints about this behaviour on my skin's forum threads so I thought looking into it.

@Ignoble61 Welcome back ;-) Hope you and your family are doing fine?
I was hoping if you could shine a light on this? Was this the expected behaviour?

If so, I'm thinking about adding an extra menu action to just change the action (and choose from the list) instead of wiping the full shortcut.

I can/will pick this one up myself (if nobody beats me to it), it's just a reminder that I need to do this and maybe someone else has an opinion about this.

**Comment by ghost** [comment]
Hello @marcelveldt, nice to see you and, without going into too much detail, yes my family are doing fine and, indeed, I'm going to have three generations of my family living in one house for a couple of months whilst housing sales go through, which I'm both looking forward to an incredible amount, and dreading on every level ;) Hope you are keeping well, too, and congratulations on the birth of your offspring.

Wow, this is code I haven't looked at in a hell of a long time, so forgive me that everything I write is based on memory and not necessarily fact, but no - I don't think this is intended behaviour.

The problem is that when the action is changed, so is the labelID. The script keeps a list of labelID changes, and then - when the menu is saved - applies the previous additional properties from the previous labelID to the item with the new labelID. If my memory of all this is correct, then something's going wrong with either the saving of the previous labelID, or of the applying additional properties to the new item.

**Comment by ghost** [comment]
Thinking off the top of my head (I'll take a proper look tomorrow, if no-one beats me too it) - since that code was written, the defaultID property was added - this may be a far better way of migrating properties from one item to another (an item with a new action is always considered a new item)...

**Comment by ghost** [comment]
I'm unable to reproduce this, using Conq as a base test. When choosing a new shortcut via control 401, the action, label and thumbnail are all changed to that of the newly selected shortcut (expected behaviour).

The selected widget and background aren't changed, and it stays linked to the submenu.

**Comment by marcelveldt** [comment]
Great to hear you're doing fine and glad to see you back here sharing your great ideas here with us.
Wow, that's a whole house full, can imagine that's fun in the beginning but very dreading in the longer term ;-)
Yes, I'm doing fine too. Enjoying every aspect of the newborn babygirl, it's a big change beiing a father but wouldn't give it up for all the money in the world :-)

Well, about that shortcuts "issue". I will do some more tests. It was reported a couple of times on my skin's forum thread, and saw some of the same reports on other skin theeads too. Users expect that when changing the action for a tile it will keep all of it's properties including label, icon and stuff. So basically they just want to switch the action to something else. For example you have a shortcut configures for "Live TV". You have it all setup with your favorite icon, label, background and possibly a widget or submenu. If that shortcut opens the "channels" by default and you just want to change the action to open the "guide" view instead you'd loose all customizations you've set. 

I'm thinking of adding an extra button control ID, which will when pressed only change the action. 
I do not want to load you with all kinds of feature requests so I'm happy to add this in myself if you could point me a little in the right direction ;-)

**Comment by ghost** [comment]
I'm not sure I agree - if I change my Live TV shortcut to, say a specific channel, it wouldn't make sense to me if the label didn't change to reflect that. And I'd also loose my only opportunity to have the icon automatically set to the channels logo. I can see where people are coming from, though, if they change they are making is relatively small, such as your example.

Point in the right direction? gui.py, line 1242 (if controlID == 401). At the very least, you won't want to be using 

`listitemCopy = self._duplicate_listitem( selectedShortcut, self.getControl( 211 ).getListItem( num ) )`

as that's where the behaviour you don't like is happening. You can probably just update the action directly (look at control 307 for example), but you'll want to think through the expected behaviours in different scenarios - for example, I would expect if I created a 'New' shortcut, that even setting just the action would set everything (because it would otherwise still be without a label and icon)...

(And sorry if I'm getting confused here between the icon and the thumbnail. One of them /shouldn't/ be overwritten when changing the shortcut, and it's the one that takes priority within the skin/the one that Skin Shortcuts lets the user pick their own for)

An alternative might be to only overwrite the label, icon (they are the only things which should be getting overwritten I think, aside from the action itself) if the user hasn't personalised them. Your choice :)

**Comment by ghost** [comment]
Y'know, if I were to implement this (don't get me wrong, I'm not going to), I'd just extend control 307 (edit action) to give the choice to type a new action or browse for one. That way, the whole select shortcut methodology (where the whole shortcut - label, icon and all - are changed) stays, and the edit action does exactly what it says on the tin, just with a lot more features.

**Comment by marcelveldt** [comment]
I think you're right. It depends on the situation if you want to just change the whole shortcut or change it's action. Those are two completely different things. I will take a look at your suggestion to extend the method for button 307, that would be best.

Thanks!

**Comment by ghost** [comment]
Please see PR referenced above - I found a bug whereby, on a new main menu (a new installation, or after resetting all shortcuts), the submenu would get de-linked if the shortcut was changed before the main menu was saved. Shouldn't impact the issue you've raised, but you never know.

**Comment by marcelveldt** [comment]
changed the edit shortcut action to present the library dialog and allow the user to enter a custom action
