### ISSUE TITLE
feature request: back button while browsing shortcuts

### ISSUE THREAD

**Issue by marcelveldt** [BigNoid/script.skinshortcuts#32]
while browsing a layered structure if you want to pick a shortcut there is no way to go back.
would be nice if there was a back button in the list to move up the tree.

**Comment by ghost** [comment]
One third of the code to do this is already in place, though weirdly enough I removed it from my WIP widgets branch a few days ago because its not in use (and isn't very useful in its incomplete form).

OK, so available shortcuts are displayed via two methods - LIBRARY.selectShortcut (displays the hierarchy as defined in the overrides.xml grouping) and LIBRARY.explorer (to explore library & add-on nodes).

Within explorer, you can uncomment lines somewhere around the 1110 mark to add a ".." option which will go back 'up' (as far as the top level of the library/add-on.)

selectShortcut would need the same implementing - it's actually pretty simple code, and actually probably able be able to be implemented in a simpler form here than in explorer (because this displays what the xml tells it to, not what we get from a json call). The function is called recursively, so a 'history' list needs to be passed along, with the new 'level' being shown added each time, or popped in the case of going back.

The last piece would be going back from explorer to selectShortcut - a simple call which then gets selectShortcut to display it's current 'level' again.

So very doable, if someone wants to take it on ;) (I'll look at it myself when I have time, but that won't be for a little while unless I can fairly quickly add it to the widgets branch)

**Comment by ghost** [comment]
Ah, the wonders of insomnia - https://github.com/Ignoble61/script.skinshortcuts/commit/1d6cd186c7e0a938c8b8aa26aa3062284983357d

**Comment by marcelveldt** [comment]
Wow, that was really quick! Thanks!
