### ISSUE TITLE
FR: customize property dialog

### ISSUE THREAD

**Issue by marcelveldt** [BigNoid/script.skinshortcuts#57]
A feature request to be considered, submitted by tomer953 on the Kodi forums:
http://forum.kodi.tv/showthread.php?tid=178294&pid=2087427#pid2087427

Some requests about the Custom property method.
1. Custom Title for the choosing dialog
2. Default value for the property, so Every new item will have the default value
3. option to remove the "none" option
   
   for example, I have:

```
    <property property="Icon_Overlay">31140</property> <!-- Same as Text color -->
     <property property="Icon_Overlay">31142</property> <!-- Same as Skin color -->
     <property property="Icon_Overlay">31141</property> <!-- Original Icon Color (no overlay) -->
```

http://i.imgur.com/jTz7Yw5.png

 and I want to add custom title to the dialog, and set default value to 31142,so maybe adding new feature like: 

```
<property id="Icon_Overlay" title="Custom Title" default="31142"/>
```

or something similar.
 Also in that case, sometimes when I send click to "404" for one custom property (lets say choose color) the choose property dialog for other button (choose icon color) is opening right after the first one .
 so I'm getting dialog after dialog when I just requested one of them. but If Ill have custom title I'll wont care, because the user will know what he is setting.

**Comment by ghost** [comment]
I'm not overly familiar with the code, but some of these sound both very sensible and (without looking into the code!) not too likely to cause breakages, if someone wanted to look at them before a stable push.
- Custom title - if only a single dialog is ever used, an override. Otherwise, done via a property set before sending a click?
- Default value - no comment, don't know the code well enough ;)
- Option to remove 'None' value - Same comments as for custom title.
