### ISSUE TITLE
skinshortcuts making kodi not to load skins properly

### ISSUE THREAD

**Issue by svillar** [BigNoid/script.skinshortcuts#72]
This is what I got from the kodi.log. The script cannot store the xml file so the skin is not properly loaded next time a kodi session is started

Traceback (most recent call last):  
00:54:53 165.851669 T:2638214176   ERROR:   File "/home/osmc/.kodi/addons/script.skinshortcuts/resources/lib/xmlfunctions.py", line 196, in shouldwerun
00:54:53 165.873596 T:2638214176   ERROR:     hashes = ast.literal_eval( xbmcvfs.File( os.path.join( **masterpath** , xbmc.getSkinDir() + ".hash" ) ).read() )
00:54:53 165.874313 T:2638214176   ERROR:   File "/usr/lib/python2.7/ast.py", line 49, in literal_eval
00:54:53 165.885696 T:2638214176   ERROR:     node_or_string = parse(node_or_string, mode='eval')
00:54:53 165.886215 T:2638214176   ERROR:   File "/usr/lib/python2.7/ast.py", line 37, in parse
00:54:53 165.886871 T:2638214176   ERROR:     return compile(source, filename, mode, PyCF_ONLY_AST)
00:54:53 165.887756 T:2638214176   ERROR:   File "<unknown>", line 0

**Comment by ghost** [comment]
Please post a link to a full debug log (enabling skin shortcuts own debug logging from its settings), and explain exactly what you mean by "the skin is not properly loaded" - link to screenshots if necessary :)

**Comment by svillar** [comment]
Ok I will.

BTW "the skin is not properly loaded" means that no matter which skin you choose (any using skinshortcuts, because the bug does not happen with confluence for example) kodi is always using the default one (in this case OSMC default skin). After some minutes, a notification is shown with the text "Skin Shortcuts. Creating menu...", then "Writing menu...", for some time. Once the notification is gone the selected skin is properly loaded. Not for so long, because as soon as you log out and log in again (I'm using user profiles) the same sequence of events happen (default skin -> skinshortcut notification -> selected skin).

**Comment by ghost** [comment]
Thanks for the clarification (and looking forward to the debug log :wink:). Can I just confirm, when logging in again, the system reverts to the default skin, then the skin shortcuts build notification shows, before the skin switches to the selected skin? If so, what is the behaviour when going into a part of the library, the Movie library for example, and then returning to the home page - does the build notification show again?

~~I haven't got time to look into the problem properly until next week (no access to a system I can code on), but this is the second report of this and, with this extra information, some conclusions can start to be drawn.~~

~~So, it looks like the menu is being written properly, as is the .hash file (this file contains details of what data has been used to write the menu - which .DATA.xml files, which skin version, which Kodi version, etc, and is a large part of deciding whether to write a new menu) which the error linked to above is trying to read (either failing would result in a dialog being shown to the user indicating the menu failed to be built). The problem is that the .hash file can't be read by the ast.literal_eval function when deciding if the menu needs to be rebuilt, resulting in an automatic rebuilding of the menu (the script acts, in this case, as if the .hash file doesn't exist).~~

~~The ast function is a change in the latest version of the script - the file is just a python dict element  converted to a string via repr and written to disk. In previous versions it was reloaded via the eval command. This was changed in the latest version as the eval command will execute arbitrary python code, and so is a potential security issue. The literal_eval function won't, it will just load python objects.~~

~~So, the obvious conclusions (though it could, of course, be something more subtle) is either the ast.literal_eval command is failing on specific platforms or due to some other issue (such as unicode issues, though I would expect those to have shown up by now with whose tested beta versions, and to produce a more specific error message), or the .hash file is being written incorrectly in some way - the previous report mentioned an incorrect use of the levels property in the build command, for example (though I couldn't reproduce this). @svillar - if you're able, could you also upload a copy of the id.of.the.skin.that.youre.using.hash file from your userdata/addon_data/script.skinshortcuts folder and post a link here - that will help identify if its the second issue.~~

~~Possible resolutions are to work out why the .hash file can't be read and fix it; revert to using eval to read the file (not ideal as, as said, eval is a potential security issue); switch the .hash file to an xml format (we already have all the xml libraries imported, and the hash code is relatively simple - should be a comparatively easy change.) Obviously depends on working out exactly why this is going wrong.~~

Edit:- From further information, it appears the .hash file is being saved and read correctly.

More confusing is the switching back to the default skin - nothing skin shortcuts does should cause Kodi to revert skins (as far as the skin goes, it's just writing an extra file for it to include - if the included file is not there or even unreadable, the skin should still operate perfectly fine albeit without the skinshortcuts menus). But hopefully a debug log will shed light on this particular issue (otherwise, I'm tempted to say this is an OSMC specific issue)

As I say, this is the second report I've read of this. If this is a widespread issue, @BigNoid and @marcelveldt, is it worth considering a quick fix on the repo once the issue has been properly identified, confirmed not an OSMC bug, and fixed?

**Comment by svillar** [comment]
So the answer to the first question is yes. I log in again, the default skin is shown, then the notification, and after some time, the skin I had previously selected. BTW I have noticed that my description was not totally accurate, in the sense that the notification and skin change do not happen automatically. I have to go to settings-skin etc to change the skin to the one I want and then it's when the whole thing starts.

So [these](http://paste.osmc.io/ijaxexumoq.vbs) are the contents of the hash for maxinimalism theme. As it might be an architecture specific issue, it's worth mentioning that this is running on a rpi1 althought there are [reports](https://discourse.osmc.tv/t/skin-regularly-reverts-to-osmc-standard-skin-after-reboots-by-itself-since-last-update-on-my-vero/6902/19) for other devices too.

**Comment by ghost** [comment]
Thanks for that.

~~Can you please confirm that that is the complete .hash file - the file you linked is an incomplete file suggesting either you didn't paste the whole file, or Kodi wasn't able to write the whole file. There is no reason, unless it is OS specific, that it would be written incomplete like that. And, based on the additional info you supplied, it is indeed incomplete ;)~~

Edit:- Ignore that, it seems my browser didn't open it completely. That file looks complete, and there is nothing in there (without testing, which I can't do atm, and based on your most recent comments) which would mean it can't be read correctly.

And thanks for the additional information. It means most of what I wrote above can be ignored (which is a good thing!) - the .hash file is being written and read correctly. The fact that the menu is being rebuilt isn't because the .hash file is incorrect, but because it doesn't match between the skin that has been selected and the default OSMC skin (which I understand also uses skin shortcuts). The issue is one of Kodi loading the default skin, rather than the skin you selected.

The fact that there are multiple reports on the OSMC forums (when there is only one comparative report on the Kodi forums, and that is not confirmed as being the same issue though I have asked the original reporter for more details) suggests it is an OS specific issue. Feel free to link to this issue on the OSMC forums as I'm sure the developers there are active on GitHub, though I don't know them to ping them here - if they're interested, I'm very willing to work with them on here to identify, track down and fix the issue if it is indeed related to skin shortcuts :) (A good test of whether it is or not would be to install a non-skinshortcuts script - Transparency springs to mind - and see if the issue still occurs)

Further edit:- Though I see you say you're using the Maximinalism theme. To the best of my knowledge (unless you're using a git version I don't know about), this isn't a skin which uses the skin shortcuts script, which would confirm this as not being a skin shortcuts issue :) The fact you're seeing the skin shortcuts build message is because OSMC's default skin does, not because the skin you are using does!

**Comment by svillar** [comment]
@Ignoble61 first of all, many thanks for being so responsive. Regarding why I reported this to skinshortcuts is basically because I saw the error in the logs, and also because if I choose confluence (the former default skin) which does not use skinshortcuts, then the problem is gone.

[Reported BTW](https://discourse.osmc.tv/t/skin-regularly-reverts-to-osmc-standard-skin-after-reboots/8284) on OSMC forums. Let's see what we can get :)

**Comment by ghost** [comment]
You're very welcome. Even though from what I can see it doesn't look like a skin shortcuts issue (the fact that Confluence isn't reverting to the default skin doesn't necessarily mean its a skin shortcuts issue if another non-skin shortcuts skin - maxaminimalism is - and the error you are appears appears, from what you've said, purely to be OSMC reverting to the default skin and that skin trying to build the menu when Kodi is reporting to the script another skin is actually selected) I'll leave the issue open for now and see what the OSMC people say :)

**Comment by ghost** [comment]
OSMC forums are suggesting this is a known bug in Kodi with multiple profiles, so I'm going to close this issue now. If, though, new information comes to light please feel free to re-open.

**Comment by svillar** [comment]
BTW I've finally found the issue and it's indeed in the skin shortcuts plugin. Will send a pull request ASAP.

**Comment by svillar** [comment]
Correction, the bug is already fixed upstream.
